### ISSUE TITLE
call to debug() method is causing an exception

### ISSUE THREAD

**Issue by satishgoda** [LeGoffLoic/Nodz#1]
Looks like its not in the API implementation.

https://github.com/LeGoffLoic/Nodz/blob/master/nodz_demo.py#L173

And thank you very much for making this available and also with a generous MIT license.

**Comment by LeGoffLoic** [comment]
removed ! thanks for spotting this one !

**Comment by satishgoda** [comment]
My pleasure. I have started tinkering with the API. Looks good so far.
