### ISSUE TITLE
Some Pull requests should be accepted

### ISSUE THREAD

**Issue by glm-ypinczon** [LeGoffLoic/Nodz#12]
Hi @LeGoffLoic ,
First of all, let me tell you that this library is really nice to use: it's both simple and powerful enough to start having a node UI on any application. And on a plus side, there is not many dependencies, which contributes to make it easy to use.

I think it could become a nice generic python node UI, but it needs to be maintained / upgraded in some way, otherwise everyone will just maintain it's own branch, and it'll make it hard for new comers to get what they need from all the existing branches.
And maintaining it means accepting, refusing, or at least commenting on the pull-requests to let know of were the dev is going, and how additions should be done.

As you can see, the few additions I needed for this UI to work great for my usage were pull-requested, so that everyone could benefit of them, which is the opensource way of thinking.

But doing clean pull-requests on branches that starts from your master branch (to ensure it doesn't bring changes from other branches as well and that the global graph remains clear) will become quite difficult if previous pull-requests are never accepted.
The fact is that most of my development were made outside of Maya (it's way faster to debug and check), so the bare minimum I need is the pullrequest#3 by @coderbone (https://github.com/LeGoffLoic/Nodz/pull/3).
My process to be able to work from the @coderbone branch but still doing clean pull-requests is:
 - temp dev branch from @coderbone develop branch
 - test and commit on this branch
 - dev branch from your master branch
 - cherry pick my commit from the tmp branch
 - pull-request the clean branch from you master branch

I did it for my dev until now, but it's a too time-consuming process for me to continue this way, and next pull-request might be from the develop branch directly.

Please just let us know if you wish to accept some pull request and drive this repo the way you want, or if you consider it's now everyone's job to start from this repo and go in any direction they want. it's all fine with me either, just need to know ;)

Once again, thanks for the nice work you did on this repo, will be quite useful ;)
Cheers,
Yann

**Comment by LeGoffLoic** [comment]
Hello, 

I've been really busy lately and also took a break from this project so I don't have to jump back on it when I get home.

I will take a look this weekend, from the notifications I ve received, I think most of them will be accepted.

**Comment by glm-ypinczon** [comment]
Great to know it's still alive, thanks to let us know ;)
