### ISSUE TITLE
Project packaging

### ISSUE THREAD

**Issue by csaez** [LeGoffLoic/Nodz#19]
It would be great to formalize the project by packaging it following python std practices, so it's a bit easier to make it talk with python's ecosystem and integrate it to existing code-bases (i.e. pip, requirements, versioning, virtualenv friendly and so on).
https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/creation.html

**Comment by LeGoffLoic** [comment]
Hello, sorry for the late reply,
I agree but I've never learnt how to do that and don't have time to look into this at the moment.

**Comment by LeGoffLoic** [comment]
It can now be installed with pipenv. Should make things a bit easier.
#37 
I'm going to close for now but if you think more can be done, I can look into it some more.
