### ISSUE TITLE
upgrade documentation/installation process

### ISSUE THREAD

**Issue by neodark** [LeGoffLoic/Nodz#30]
Hello,

this project seems quite interesting. However, I don't understand the installation process to get things running and what file should be launched
Could you give me a detailed explanation on how to install and launch the demo (or main?) please?

Thanks in advance for your answer.

**Comment by predat** [comment]
This not really a issue...
You just need to read the Readme.md and launch:
python nodz_demo.py

😬

**Comment by neodark** [comment]
I read the Readme.md and I guess I had wrong PYTHONPATH when I tried yesterday.
Sorry for the noise! :wink: 

However I feel there's a lack of proper documentation to put your hands in the code and start using it. Another missing thing is the requirements.txt for the installation process.

Do you plan to have a more complete documentation of the code ?

I can help you with the installation process to make things easier if you wish?

**Comment by LeGoffLoic** [comment]
@neodark Sure thing it you have some time, I'm open to suggestions

**Comment by LeGoffLoic** [comment]
I will rename this issue to "upgrade documentation/installation process"

**Comment by LeGoffLoic** [comment]
Hey @neodark 
There is now an installation possible with pipenv so you don't have to install things separately. Check the new readme.
#37
