### ISSUE TITLE
Setting the background color

### ISSUE THREAD

**Issue by jonasmmiguel** [LeGoffLoic/Nodz#31]
How can I set the panel background color (i.e. the Qt Scene color)? I couldn't find any reference neither in _default_config.json_ nor in _nodz_main.py_

**Comment by dangerfx** [comment]
bump...

**Comment by dangerfx** [comment]
here's a hack:

default_config.json:

"background_color": [69, 69, 69, 69],

nodes_main.py > def __init__(self, parent, configPath=defaultConfigPath):

        # Set Window Background.
        config = self.config
        color = config['background_color']
        self.setStyleSheet("background-color: rgb({},{},{});".format(color[1], color[2], color[3] ))

**Comment by LeGoffLoic** [comment]
This should now be available in v1.3.1
