### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by Luk3M** [LeGoffLoic/Nodz#32]
With Python 2 being retired [next year](https://pythonclock.org/), it could be nice to upgrade the code to Python 3.

It will mainly be changes on the `print` function and `unicode`.

**Comment by LeGoffLoic** [comment]
Hey @Luk3M,
I will be looking into this soon

**Comment by LeGoffLoic** [comment]
Should be done now. (closing) feel free to reopen if I've missed things.
#37
